.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH D-RATS_MAPDOWNLOADER 1 "July 15, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
d-rats_mapdownloader \- The D-RATS map download utility
.SH SYNOPSIS
.B d-rats_mapdownloader
.br
.SH DESCRIPTION
This manual page documents briefly the
.B d-rats_mapdownloader
command.
.PP
\fBd-rats_mapdownloader\fP is the D-RATS map download utility.
It will attempt to fetch all of the required tiles for a given
center location and desired diameter. The diameter is determined
by the zoom level limit.  All zoom levels below the one selected
are fetched.  D-RATS defaults to zoom level 14, so it is recommended
that you choose at least that level to fetch.  This operation
fetches a lot of small files and can take quite a long time.

The user will be prompted for the latitude and longitude of the center
location and for the diameter.
.SH OPTIONS
This program has no options.
.SH AUTHOR
d-rats_mapdownloader was written by Dan Smith.
.PP
This manual page was written by Steve Conklin,
for the Debian project (and may be used by others).
